_target_: "kubernetes"
trackingUri: "http://mlflow.local"
# Ajoutez les informations d'identification si nécessaire
# username: "admin"
# password: "zLPGwPxNiQ"

experiment:
  name: "p7-sentiment-analysis"
  run:
    name: "lstm_bidirectionnal"  # Nom de l'exécution MLflow
    description: "Training with LSTM bidirectionnelle"  # Description de l'exécution
    tags:  # Métadonnées supplémentaires
      modelType: "lstm_bidirectionnal"
      datasetVersion: "v1.0"
