_self_: "defaults"
defaults:
  - dataset: dataset-v1
  - dataPreprocess/cleaner@cleaner: cleaner-v1
  - dataPreprocess/partitioner@partitioner: trainTest
  - dataPreprocess/normalizer@normalizer: lemmatization
  - dataPreprocess/vectorizer@vectorizer: glove
  - mlflow: kubernetes-local
  - train/BERT@model: model
  - train/BERT@training: training
  - train/BERT/tuning@tuning: grisSearch
  - test: finalTest

strategy:
  description: "Validation rapide avec Train/Test avec GridSearchCV"
  use_case: "Model avancé"
