_self_: "defaults"
defaults:
  - dataset: dataset-v1
  - dataPreprocess/cleaner@cleaner: cleaner-v1
  - dataPreprocess/partitioner@partitioner: trainTest
  - dataPreprocess/normalizer@normalizer: lemmatization
  - dataPreprocess/vectorizer@vectorizer: tfidfVectorizer
  - mlflow: kubernetes-local
  - train/bidirectionalLSTM@model: model
  - train/bidirectionalLSTM@training: training
  - train/bidirectionalLSTM@tuning: tuning
  - train/bidirectionalLSTM/tuning/type@tuningType: optuna
  - test: finalTest

strategy:
  description: "Validation rapide avec Train/Test"
  use_case: "Prototypage"
