defaults:
  - dataset: dataset-v1
  - cleaner: cleaner-v1
  - normalizer: lemmatization
  - vectorizer: tfidfVectorizer
  - mlflow: local
  - partitioner: crossValidation
  - model: logisticRegression
  - hyperparameterOptimization: gridSearch
  - validation: crossValidation
  - evaluator: final
strategy:
  description: "Validation rigoureuse avec k-folds"
  use_case: "Robustesse avec peu de données"

