_self_: "defalts"
defaults:
  - dataset: dataset-v1
  - cleaner: cleaner-v1
  - normalizer: lemmatization
  - vectorizer: tfidfVectorizer
  - mlflow: kubernetes-local
  - partitioner: trainTest
  - model: logisticRegression
  - train: gridSearch
  - test: finalTest
strategy:
  description: "Validation rapide avec Train/Test"
  use_case: "Prototypage ou tests exploratoires"
