_self_: "defalts"
defaults:
  - dataset: dataset-v1
  - cleaner: cleaner-v1
  - partitioner: trainTest
  - normalizer: lemmatization
  - vectorizer: tfidfVectorizer
  - mlflow: kubernetes-local
  - model: train/bidirectionalLSTM/model #logisticRegression
  - tuning: train/bidirectionalLSTM/tuning/optuna
  - test: finalTest
strategy:
  description: "Validation rapide avec Train/Test"
  use_case: "Prototypage"
