defaults:
  - dataset: dataset-v1
  - cleaner: cleaner-v1
  - normalizer: lemmatization
  - vectorizer: tfidfVectorizer
  - mlflow: local
  - partitioner: trainValTest
  - model: logisticRegression
  - hyperparameterOptimization: gridSearch
  - validation: crossValidation
  - evaluator: final
strategy:
  description: "Combiner une GridSearchCV pour le tuning des hyperparamètres avec une validation croisée finale pour une évaluation robuste"
  use_case: "Comparaison rigoureuse"

