defaults:
  - dataset: datasetV1          # Choix du dataset par défaut
  - strategy: trainValTest      # Stratégie par défaut
  - model: p7-sentiment-analysis/logisticRegression   # Modèle par défaut
  - vectorizer: tfidfVectorizer # Vectorizer par défaut
  - hyperparameterOptimization: gridSearch
  - validation: crossValidation # Validation par défaut
