defaults:
  - dataset: dataset-v1
  - cleaner: cleaner-v1
  - normalizer: lemmatization
  - vectorizer: tfidfVectorizer
  - mlflow: kubernetes-local
  - partitioner: trainTest
  - model: logisticRegression
  - hyperparameterOptimization: gridSearch
  - validation: none
  - evaluator: none
strategy:
  description: "Validation rapide avec Train/Test"
  use_case: "Prototypage ou tests exploratoires"
