stages:
  generate_config:
    cmd: python scripts/generate_config.py
    deps:
      - scripts/config
    outs:
      - data/output/clean_data_config.yaml
      - data/output/normalize_data_config.yaml
      - data/output/vectorize_data_config.yaml
      - data/output/split_data_config.yaml
      - data/output/model_config.yaml
      - data/output/train_config.yaml
      - data/output/test_config.yaml

  clean_data:
    cmd: python scripts/clean_data.py
    deps:
      - data/output/clean_data_config.yaml
      - data/input/training.1600000.processed.noemoticon.utf-8.csv
      - scripts/clean_data.py
    outs:
      - data/output/clean_data.csv

  normalize_data:
    cmd: python scripts/normalize_data.py
    deps:
      - data/output/normalize_data_config.yaml
      - data/output/clean_data.csv
      - scripts/normalize_data.py
    outs:
      - data/output/normalize_data.csv

  vectorize_data:
    cmd: python scripts/vectorize_data.py
    deps:
      - data/output/vectorize_data_config.yaml
      - data/output/normalize_data.csv
      - scripts/vectorize_data.py
    outs:
      - data/output/vectorize_data.pkl
      - data/output/vectorizer.pkl

  split_data:
    cmd: python scripts/split_data.py
    deps:
      - data/output//split_data_config.yaml
      - data/output/vectorize_data.pkl
      - scripts/split_data.py
    outs:
      - data/output/split_data.pkl

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - data/output/model_config.yaml
      - data/output/train_config.yaml
      - data/output/split_data.pkl
      - scripts/train_model.py
    outs:
      - data/output/mlflow_id.json

  test_model:
    cmd: python scripts/test_model.py
    deps:
      - data/output/mlflow_id.json
      - data/output/test_config.yaml
      - data/output/split_data.pkl
      - scripts/test_model.py

dvc remote add -d myremote s3://p7-sentiment-analysis

dvc remote modify myremote access_key_id admin
dvc remote modify myremote secret_access_key XKzq2CuGKQ
dvc remote modify myremote endpointurl  http://api.minio.local        

remote:
  myremote:
    url: s3://p7-sentiment-analysis
