stages:
  generate_config:
    cmd: python scripts/generate_config.py
    deps:
      - scripts/config
    outs:
      - data/output/clean_data_config.yaml
      - data/output/split_data_config.yaml
      - data/output/normalize_data_config.yaml
      - data/output/vectorize_data_config.yaml
      - data/output/model_config.yaml
      - data/output/train_config.yaml
      - data/output/test_config.yaml

  clean_data:
    cmd: python scripts/clean_data.py
    deps:
      - data/output/clean_data_config.yaml
      - data/input/training.1600000.processed.noemoticon.utf-8.csv
      - scripts/clean_data.py
    outs:
      - data/output/clean_data.csv

  split_data:
    cmd: python scripts/split_data.py
    deps:
      - data/output/split_data_config.yaml
      - data/output/clean_data.csv
      - scripts/split_data.py
    outs:
      - data/output/split_data.pkl

  normalize_data:
    cmd: python scripts/normalize_data.py
    deps:
      - data/output/normalize_data_config.yaml
      - data/output/clean_data.csv
      - scripts/normalize_data.py
    outs:
      - data/output/normalize_data.pkl

  vectorize_data:
    cmd: python scripts/vectorize_data.py
    deps:
      - data/output/vectorize_data_config.yaml
      - data/output/normalize_data.csv
      - scripts/vectorize_data.py
    outs:
      - data/output/train_ready_data.pkl
      - data/output/vectorizer.pkl

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - data/output/model_config.yaml
      - data/output/train_config.yaml
      - data/output/train_ready_data.pkl
      - scripts/train_model.py
    outs:
      - data/output/mlflow_id.json

  test_model:
    cmd: python scripts/test_model.py
    deps:
      - data/output/mlflow_id.json
      - data/output/test_config.yaml
      - data/output/train_ready_data.pkl
      - scripts/test_model.py