_version_: "v1"
_target_: "cleaner"
remove_urls: true
remove_mentions: true
remove_hashtags: true
lowercase: true
remove_punctuation: true
strip_whitespace: true
input: "./data/input/training.1600000.processed.noemoticon.utf-8.csv"
output: "./data/output/clean_data.csv"
