type: "optuna"
trialCount: 50               # Nombre maximum d'essais pour Optuna
timeLimitSeconds: 1200       # Temps limite en secondes pour le tuning
optimizationDirection: "maximize"  # Maximiser une métrique (ex: validation accuracy)

# Hyperparamètres à optimiser
paramGrid:
  embedding_dim: [50, 100, 200, 300]           # Dimensions des embeddings
  lstm_units_1: [32, 64, 128]                  # Nombre d'unités pour la première couche LSTM
  lstm_units_2: [32, 64, 128]                  # Nombre d'unités pour la seconde couche LSTM
  dropout_rate: [0.1, 0.2, 0.3, 0.4, 0.5]      # Taux de dropout pour éviter l'overfitting
  dense_units: [32, 64, 128]                   # Nombre d'unités dans la couche Dense
  batch_size: [16, 32, 64]                     # Taille du batch pour l'entraînement
  epochs: [5, 10, 15]                          # Nombre d'époques pour l'entraînement
  optimizer: ["adam", "rmsprop", "sgd"]        # Optimiseur

