# Type de vectorisation : "count" pour Bag of Words
_target_: "countVectorizer"

# Chemins pour la sauvegarde ou le chargement
outputPath: "../data/output/bow_vectorizer.pkl"      # Où sauvegarder le vectoriseur
outputData: "../data/output/bow_vectorized_data.pkl" # Où sauvegarder les données transformées

# Paramètres pour réutiliser un vectoriseur ou des données déjà calculées
existingVectorizer: false  # Chemin vers un vectoriseur existant (si réutilisation)
existingData: false        # Chemin vers des données transformées existantes (si réutilisation)

# Options additionnelles éventuelles pour CountVectorizer
min_df: 1
max_df: 1.0
ngram_range: [1, 1]
stop_words: null
