_target_: "tfidfVectorizer"
enabled: true   
stopWords: "english"
maxFeatures: 1000
ngramRange: [1, 2]
# Chemins pour la sauvegarde ou le chargement
outputPath: "../data/output/vectorizer.pkl"      # Où sauvegarder le vectoriseur
outputData: "../data/output/vectorized_data.pkl" # Où sauvegarder les données transformées
existingVectorizer: false                        # Chemin vers un vectoriseur existant (si réutilisation)
existingData: false                              # Chemin vers des données transformées existantes (si réutilisation)