earlyStopping:
  enabled: false
  patience: 3
  monitor: "val_loss"
  mode: "min"

learningRateScheduler:
  enabled: false
  factor: 0.5
  patience: 2
  min_lr: 1e-5
  monitor: "val_loss"

input: "data/output/train_ready_data.pkl"