_target_: "bidirectionalLSTM"
type: "bidirectional_lstm"
vocab_size: 10000  # Taille du vocabulaire
embedding_dim: 100  # Dimension des embeddings
max_length: 100  # Longueur maximale des séquences
lstm_units:
  - 128
  - 64
dense_units: 32
dropout_rate: 0.5
output_activation: "sigmoid"
loss_function: "binary_crossentropy"
optimizer: "adam"
metrics:
  - "accuracy"
batch_size: 32
epochs: 5


