_target_: "bidirectionalLSTM"
type: "bidirectional_lstm"
vocab_size: 10000  # Taille du vocabulaire
embedding_dim: 50
  - 128  # Augmenté pour plus de capacité
dense_units: 64
dropout_rate: 0.3
output_activation: "sigmoid"
loss_function: "binary_crossentropy"
optimizer: "adam"
metrics:
  - "accuracy"
batch_size: 32
epochs: 5


