paramGrid:
  embedding_dim: [50, 100, 200, 300]
  lstm_units_1: [32, 64, 128]
  lstm_units_2: [32, 64, 128]
  dropout_rate: [0.1, 0.2, 0.3, 0.4, 0.5]
  dense_units: [32, 64, 128]
  batch_size: [16, 32, 64]
  epochs: [5, 10, 15]
  optimizer: ["adam", "rmsprop", "sgd"]        # Optimiseur
