_target_: "tfidfVectorizer"
_version_: "1.0.0"
stopWords: "english"
maxFeatures: 1000
ngramRange: [1, 2]
# Chemins pour la sauvegarde ou le chargement
outputPath: "data/output/vectorizer.pkl"      # Où sauvegarder le vectoriseur
outputData: "data/output/train_ready_data.pkl" # Où sauvegarder les données transformées
