name: Pipeline

on:
  push:
    branches:
      - main  # Déclencher le pipeline sur les pushs vers la branche "main".
  workflow_dispatch:  # Permet de lancer manuellement le workflow depuis l'interface GitHub Actions.

jobs:
  custom-docker-env:
    runs-on: self-hosted  # Utilisation d'un runner self-hosted pour exécuter le pipeline.

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Étape pour cloner le repository sur le runner.

      - name: Pull DVC data
        run: dvc pull  # Télécharger les données versionnées via DVC depuis le stockage distant.

      - name: Reproduce DVC pipeline
        run: dvc repro  # Reproduire le pipeline DVC, en exécutant uniquement les étapes nécessaires.

      - name: Push DVC data
        run: dvc push  # Pousser les nouvelles données générées vers le stockage distant DVC.

      - name: Launch pipeline
        run: dvc repro


