on:
  push:
    branches:
      - main  # Exécute le workflow pour les pushs sur la branche `main

jobs:
  setup-environment:
    runs-on: self-hosted
    steps:
      - name: Activer l'environnement Conda
        run: source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
      - name: Vérifier l'environnement activé
        run: conda info --envs
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check repository
        run: ls */*
      - name: Check Data
        run: ls ../data/*

  data-preprocessing:
    runs-on: self-hosted
    needs: setup-environment
    steps:
      - name: Activer l'environnement Conda
        run: |
          source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
      - name: Nettoyage des données
        run: |
          python scripts/clean_data.py
      - name: Vectorisation
        run: |
          python scripts/vectorizer.py

  model-training:
    runs-on: self-hosted
    needs: [setup-environment, data-preprocessing]
    steps:
      - name: Automatisation des entraînements
        run: |
          source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
          python scripts/train_model.py

  model-validation:
    runs-on: self-hosted
    needs: model-training
    steps:
      - name: Validation et tests rigoureux
        run: |
          source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
          python scripts/validate_model.py

  model-deployment:
    runs-on: self-hosted
    needs: model-validation
    steps:
      - name: Déploiement continu
        run: |
          source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
          python scripts/deploy_model.py

  model-iteration:
    runs-on: self-hosted
    needs: model-deployment
    steps:
      - name: Amélioration continue
        run: |
          source /opt/conda/etc/profile.d/conda.sh && conda activate mlops-env
          python scripts/iterate_model.py

